<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Hello hkit, lets complete the test form</name>
   <tag></tag>
   <elementGuidId>fe5cd0ce-1910-4fa7-8924-2aca5c1e3add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='greetings']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#greetings</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>8a0107a1-dbcf-469e-9ea4-5ef50a9cdd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>greetings</value>
      <webElementGuid>816f38a4-7dd2-4d41-b55c-f994c41f6622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hello hkit, let's complete the test form:</value>
      <webElementGuid>a5f67d33-4633-49e5-9683-e94875cf2c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;greetings&quot;)</value>
      <webElementGuid>e373da5e-6483-47a2-9b17-dd9c7e3453c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='greetings']</value>
      <webElementGuid>1a5aee74-a319-4115-bb7f-47dec16de831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pageProfile']/p</value>
      <webElementGuid>0755ad1c-5e6c-46b4-8a6a-eab1ee7a8855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestProject Example page'])[2]/following::p[1]</value>
      <webElementGuid>d783be63-dd49-44ad-995b-cc1778c8f25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::p[1]</value>
      <webElementGuid>432a60d7-c289-4e41-aefa-98358cf474c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country:'])[1]/preceding::p[1]</value>
      <webElementGuid>915e22f5-7120-459c-83bd-5bd6a5fded3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hello']/parent::*</value>
      <webElementGuid>cd2eef63-411c-44cb-8a38-c40cd231b92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>049846e6-252b-4d24-a5fd-06698b8ed6c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'greetings' and (text() = concat(&quot;Hello hkit, let&quot; , &quot;'&quot; , &quot;s complete the test form:&quot;) or . = concat(&quot;Hello hkit, let&quot; , &quot;'&quot; , &quot;s complete the test form:&quot;))]</value>
      <webElementGuid>381e8d68-851e-4be5-92d6-735f41b469f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
